[tool.poetry]
name = "pipeline_vsdi"
version = "1.0.0"
description = "Preprocessing tools for voltage sensitive dye imaging data"
authors = ["NeuroNetMem"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
scipy = "^1.10.1"
numpy = "^1.24.3"
tqdm = "^4.65.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
