[tool.poetry]
name = "vsdi pipeline"
version = "1.0.0"
description = "Preprocessing tools for voltage sensitive dye imaging data"
authors = ["NeuroNetMem"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
